# Don't use 'https' for RubyGems. They've had certificate issues in the past, 
# and HTTPS prevents the Internet from caching your files and generally 
# accellerating your downloads.
source 'http://rubygems.org'

gem "middleman", "~>3.3.3"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

# Let the system worry about vendor prefixes
gem 'middleman-autoprefixer'

# Allow pages to specify their SEO-friendly aliases
gem 'middleman-alias'

# Gems to make things small
gem "middleman-minify-html"
gem "middleman-imageoptim"

# Javascript optimizations
gem 'therubyracer'
gem 'oj'

# Templating languages
gem "builder"
gem "nokogiri"
gem "coffee-script"
gem "RedCloth"
gem "less"
gem "redcarpet"
